// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: internal/api/v1/cds.proto

package cdspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The agent server version.
type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       string                 `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_internal_api_v1_cds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_cds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_cds_proto_rawDescGZIP(), []int{0}
}

func (x *Version) GetCurrent() string {
	if x != nil {
		return x.Current
	}
	return ""
}

var File_internal_api_v1_cds_proto protoreflect.FileDescriptor

const file_internal_api_v1_cds_proto_rawDesc = "" +
	"\n" +
	"\x19internal/api/v1/cds.proto\x12\x03cds\x1a\x1bgoogle/protobuf/empty.proto\"#\n" +
	"\aVersion\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\tR\acurrent2=\n" +
	"\x05Agent\x124\n" +
	"\n" +
	"GetVersion\x12\x16.google.protobuf.Empty\x1a\f.cds.Version\"\x00B%Z#github.com/amadeusitgroup/cds/cdspbb\x06proto3"

var (
	file_internal_api_v1_cds_proto_rawDescOnce sync.Once
	file_internal_api_v1_cds_proto_rawDescData []byte
)

func file_internal_api_v1_cds_proto_rawDescGZIP() []byte {
	file_internal_api_v1_cds_proto_rawDescOnce.Do(func() {
		file_internal_api_v1_cds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_v1_cds_proto_rawDesc), len(file_internal_api_v1_cds_proto_rawDesc)))
	})
	return file_internal_api_v1_cds_proto_rawDescData
}

var file_internal_api_v1_cds_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_api_v1_cds_proto_goTypes = []any{
	(*Version)(nil),       // 0: cds.Version
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_internal_api_v1_cds_proto_depIdxs = []int32{
	1, // 0: cds.Agent.GetVersion:input_type -> google.protobuf.Empty
	0, // 1: cds.Agent.GetVersion:output_type -> cds.Version
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_v1_cds_proto_init() }
func file_internal_api_v1_cds_proto_init() {
	if File_internal_api_v1_cds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_v1_cds_proto_rawDesc), len(file_internal_api_v1_cds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_v1_cds_proto_goTypes,
		DependencyIndexes: file_internal_api_v1_cds_proto_depIdxs,
		MessageInfos:      file_internal_api_v1_cds_proto_msgTypes,
	}.Build()
	File_internal_api_v1_cds_proto = out.File
	file_internal_api_v1_cds_proto_goTypes = nil
	file_internal_api_v1_cds_proto_depIdxs = nil
}
